export { default as Login } from './Login/Login'
export { default as Home } from './Home/Home'
export { default as Recordings } from './Recordings/Recordings'
export { default as RecordingDetail } from '../pages/RecordingDetail/RecordingDetail'
export { default as Favorites } from './Favorites/Favorites'